### ISSUE TITLE
[Feature Request] Environmental Variable Support

### ISSUE THREAD

**Issue by amarz45** [green7ea/sesame#3]
I would like for the ability to use environmental variables in my sesame config:

```json
[
  {
    "protocol": {
      "http,https": [
        {
          "contains": ["youtube.com/watch?", "youtu.be/?"],
          "use": "$PLAYER"
        },
        "$BROWSER"
      ]
    }
  },

  {
    "mime": {
      "image": "$VIEWER",
      "video": "$PLAYER",
      "audio": ["$PLAYER", "--player-operation-mode=pseudo-gui", "--script-opts=osc-visibility=always"],
      "application/pdf": "$READER"
    }
  },

  ["$TERMINAL",  "-e", "vi"]
]
```

But there is a problem: The environmental variables don't work because they are wrapped in quotes:

```
/usr/bin/env: ‘$TERMINAL’: No such file or directory
```

This is because it is running `/usr/bin/env '$TERMINAL'` instead of '/usr/bin/env $TERMINAL'.

**Comment by green7ea** [comment]
Great feature request :-)

I found an easy way to do this - using `env -S`. This expands the variables and also splits the whitespace. Because of this, the previous commit allowing for arrays was no longer needed and this is a simpler version. You should now be able to get what you want with the syntax:

```
"${TERMINAL} -e ${EDITOR}"
```

I did a force push because of the revert, sorry about that inconvenience. Please let me know if this works better for you.

The `${}` is the variable format supported by env.

**Comment by amarz45** [comment]
Excellent, it works perfectly!

**Comment by amarz45** [comment]
I would also consider adding a default configuration so that users will now have to specify their own.
I think that by default, it should be something like this:

```json
[
  {
    "protocol": {
      "http,https": [
        {
          "contains": ["youtube.com/watch?", "youtu.be/?"],
          "use": "${PLAYER}"
        },
        "${BROWSER}"
      ]
    }
  },

  {
    "mime": {
      "image": "${VIEWER}",
      "video": "${PLAYER}",
      "audio": "${PLAYER} --player-operation-mode=pseudo-gui --script-opts=osc-visibility=always",
      "application/pdf": "${READER}"
    }
  },

  "${TERMINAL} -e ${EDITOR}"
]
```

Since it uses environmental variables, it will work on any system that has these set.

**Comment by green7ea** [comment]
That's a great idea but I don't know what variables are 'standard'. You have a view here that I don't have:

- `VIEWER`,
- `READER`,
- `PLAYER`.

If I can find a list of the standard ones somewhere, that should be easy to implement. I looked at freedesktop and other such places for this but couldn't find anything.

**Comment by amarz45** [comment]
I think it should first check if those environment variables exist. And if they don't exist, set them to this:

- VIEWER: nsxiv
- READER: zathura
- PLAYER: mpv
- BROWSER: firefox
- EDITOR: vi

And I think this should be how the default configuration is:

```json
[
	{
		"protocol": {
			"http,https": "${BROWSER}"
		}
	},

	{
		"mime": {
			"image": "${VIEWER}",
			"video": "${PLAYER}",
			"audio": "${PLAYER}",
			"application/pdf": "${READER}"
		}
	},

	"${EDITOR}"
]
```
